### ISSUE TITLE
provision TLS certificates

### ISSUE THREAD

**Issue by Stunt0265** [luislavena/homelab-headscale#2]
For Headscale, is there a way to get HTTPS certs for using Tailscale's proxy feature?

https://tailscale.com/kb/1153/enabling-https/

**Comment by luislavena** [comment]
Hello @Stunt0265, I don't think that is possible, at least headscale doesn't provide that.

```
$ tailscale cert
HTTPS cert support is not enabled/configured for your tailnet.
```

Then:

```
$ sudo tailscale cert mymachine.user.domain.com
[sudo] password for luis: 
500 Internal Server Error: SetDNS "_acme-challenge.mymachine.domain.com" => "YUJqq2qMEpEd....fvX6OggaDnCWi8": set-dns response: 404 Not Found, 404 page not found
```

Headscale would need to manage your DNS in order to obtain a cert via Let's Encrypt, this means that headscale will need to implement things like Cloudflare or other DNS providers in order to setup the DNS records needed by ACME challenges.

Not sure if that will happen as might be out of the core of Headscale functionality, but you could ask them.

Alternatively, you could achieve something similar using things like Caddy and their automatic TLS setup with their automatic DNS providers: https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148

https://caddyserver.com/docs/automatic-https#dns-challenge

And have Caddy for TLS termination on the nodes you need it. I know is not centralized, but at least will work for private nodes.

Hope that helps.

Cheers.
